### ISSUE TITLE
Missing attribution

### ISSUE THREAD

**Issue by seanbell** [PrincetonVision/marvin#1]
It seems like some of the code is based off Fast R-CNN, but there is no attribution of this listed anywhere.  For example, it is clear that https://github.com/PrincetonVision/marvin/blob/master/marvin.hpp#L1414 is a line-by-line refactoring of Ross's code (copyrighted by Microsoft, licensed with the MIT license).  It is important to handle copyright correctly and acknowledge that parts of the code are derivative works of other libraries.

That being said, I think this library is great and I hope people pick it up.

**Comment by xiaojianxiong** [comment]
Thanks a lot for pointing out this important issue! We will address that immediately.

**Comment by seanbell** [comment]
Thanks for the fast response!
