### ISSUE TITLE
compile error on ubuntu

### ISSUE THREAD

**Issue by lidong04** [PrincetonVision/marvin#29]
Hi,

I am new to marvin, trying to install it on a ubuntu workstation. I think I had followed the readme and got cuda 7.5 and cudnn v4rc installed properly, downloaded the latest marvin-master, but it seems marvin has some issue with compiling:

lidong@T7600:~/marvin$ which nvcc
/usr/local/cuda-7.5/bin/nvcc
lidong@T7600:~/marvin$ echo $LD_LIBRARY_PATH
/usr/local/cuda-7.5/lib64:/usr/local/cudnn/v4rc/lib64:
lidong@T7600:~/marvin$ ./compile.sh 
marvin.hpp(6274): error: argument of type "half *" is incompatible with parameter of type "cudnnTensorDescriptor_t"

marvin.hpp(6276): error: argument of type "double" is incompatible with parameter of type "void *"

marvin.hpp(6278): error: argument of type "half *" is incompatible with parameter of type "double"

marvin.hpp(6278): error: too few arguments in function call

4 errors detected in the compilation of "/tmp/tmpxft_00006d3a_00000000-9_marvin.cpp1.ii".

Anyone has any ideas?

Thanks a lot for any suggestions.

Regards,
lidong

**Comment by fyu** [comment]
Hi @lidong04 Marvin has been well tested on Ubuntu and it is hard to see what's going wrong for you. If you still have the problem, can you show some more information such as ubuntu version, marvin commit number?

**Comment by lidong04** [comment]
Hi @fyu Thanks for your reply. I understand that Marvin is well tested on ubuntu, so I think I must have missed something - and here is my ubuntu version and marvin commit number:

Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:    trusty

commit a79defb361009162baeeb83df97ef04cae312e90
Merge: 1fe98f2 9861e29
Author: Daniel Suo dsuo@post.harvard.edu
Date:   Thu Jan 7 17:34:52 2016 -0500

If it is ok, can you share your ubuntu/cuda version and/or settings which can run Marvin correctly? I can re-install ubuntu/cuda from scratch again, follow your version and/or settings.

Thank you very much,
lidong

**Comment by lidong04** [comment]
Also, here is my nvcc version:

lidong@T7600:~/marvin$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by djpetti** [comment]
Just for the record, I am experiencing this issue with the exact same version of Ubuntu.

**Comment by fyu** [comment]
@danielsuo The problem occurs at batch normalization cuDNN call. Can you have a look at it?

**Comment by djpetti** [comment]
I can confirm that rolling back before commit 9861e29ea6c924095d88ad0ace7870bc4a9d0134 fixes the issue.

**Comment by danielsuo** [comment]
We are not able to replicate the issue on Ubuntu 14.04.1 LTS or Ubuntu
15.04. Unlikely causes, but good to check:
- Do you have any other versions of cuDNN installed that may be clobbering
  v4rc?
- Have you modified compile.sh in anyway?
- Have you followed all the path installation directions from the README
  https://github.com/PrincetonVision/marvin? (For example, being able to
  echo the library path in command line does not guarantee that the
  executable itself has access to the variable)

It is also possible that there is some difference between 14.04.3 and
14.04.1.

**Comment by lidong04** [comment]
Hi @djpetti and @danielsuo Thank you very much for the comment, Rolling back before 9861e29 does fix the issue. It works fine now on my Ubuntu 14.04.3:)

**Comment by djpetti** [comment]
Hmm... What version of gcc are people using?

**Comment by fyu** [comment]
This is fixed in commit 9a3e9eb37aa6fd038db586735e00a46ff49cfaab
