### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bcd33bcd** [PrincetonVision/marvin#30]
When I use gcc-4.8 to run complie.sh , the error message reported.

marvin.hpp(6266): error: argument of type "const void *" is incompatible with parameter of type "cudnnTensorDescriptor_t"

marvin.hpp(6276): error: argument of type "half *" is incompatible with parameter of type "double"

marvin.hpp(6278): error: argument of type "double" is incompatible with parameter of type "const void *"

marvin.hpp(6279): error: too many arguments in function call

**Comment by fyu** [comment]
Updating cuDNN to 4.0 may solve the problem.

**Comment by lfwin** [comment]
I am also have this problem, my cudnn version is cudnn-7.0-linux-x64-v4.0-rc.tgz, and cudnn file is placed in /usr/local/cudnn/v4/, also i modified marvin.hpp, this line:
#include </usr/local/cudnn/v4/include/cudnn.h>
but also got errors:
marvin.hpp(6266): error: argument of type "const void *" is incompatible with parameter of type "cudnnTensorDescriptor_t"

marvin.hpp(6276): error: argument of type "half *" is incompatible with parameter of type "double"

marvin.hpp(6278): error: argument of type "double" is incompatible with parameter of type "const void *"

marvin.hpp(6279): error: too many arguments in function call

marvin.hpp(6509): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6837): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6912): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6922): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(2421): error: namespace "std::this_thread" has no member "sleep_for"
          detected during instantiation of "marvin::Tensor<T>::Tensor(std::string, int) [with T=half]" 
(3216): here

marvin.hpp(2567): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(2589): error: namespace "std::this_thread" has no member "sleep_for"

12 errors detected in the compilation of "/tmp/tmpxft_0000fd06_00000000-9_marvin.cpp1.ii".

**Comment by fyu** [comment]
@lfwin Your cudnn is release candidate. You have to go to cuDNN website to download the official release.

**Comment by lfwin** [comment]
Hi, fyu.
I am just change cudnn from release candidate to official release, errors number reduced to 8:
marvin.hpp(2202): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6509): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6837): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6912): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(6922): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(2421): error: namespace "std::this_thread" has no member "sleep_for"
          detected during instantiation of "marvin::Tensor<T>::Tensor(std::string, int) [with T=half]" 
(3216): here

marvin.hpp(2567): error: namespace "std::this_thread" has no member "sleep_for"

marvin.hpp(2589): error: namespace "std::this_thread" has no member "sleep_for"

8 errors detected in the compilation of "/tmp/tmpxft_00011b42_00000000-9_marvin.cpp1.ii".

**Comment by fyu** [comment]
That looks like your compiler is not supporting c++11 well enough.

**Comment by lfwin** [comment]
Hi, fyu
Thank you very much. Solved this by update g++ 4.73 to g++ 4.8.
