### ISSUE TITLE
compile error:identifier "CUBLAS_DATA_HALF" is undefined

### ISSUE THREAD

**Issue by SSSuperMac** [PrincetonVision/marvin#41]
I have met with the problems with installation.
compile error is here:
`marvin.hpp(2226): error: identifier "CUBLAS_DATA_HALF" is undefined
1 error detected in the compilation of "/tmp/tmpxft_00007625_00000000-9_marvin.cpp1.ii".
`
I have the Ubuntu16.04 with cuda 8.0 and cudnn5.1

**Comment by jianxiongxiao** [comment]
It is caused by some changes in CUDA 8.0. We have fixed it. Please download the latest version of Marvin from github again. Thanks.
